server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

        - id: market
          uri: lb://market-service
          predicates:
            - Path=/api/market/**
          filters:
            - StripPrefix=2

        - id: analytics
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=2
security:
  jwt:
    jwk-set-uri: "http://auth-service:8081/.well-known/jwks.json"
    issuer: "auth-service"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
